# Generated by Django 3.2.8 on 2021-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211009_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(default=1, upload_to='product_photos'),
            preserve_default=False,
        ),
    ]
