# Generated by Django 3.2.8 on 2021-10-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='author',
        ),
    ]
